language: go

go:
 - 1.6

services:
 - postgresql

install:
 # tools
 - go get -tags "nomymysql nomysql nosqlite3" github.com/CloudCom/goose/cmd/goose
 - go get github.com/golang/lint/golint
 - go get github.com/GeertJohan/fgt
 # coveralls
 - go get github.com/mattn/goveralls
 - go get golang.org/x/tools/cmd/cover
 # dependencies
 - go get github.com/jmoiron/sqlx
 - go get github.com/lib/pq
 - go get gopkg.in/yaml.v2
 - go get github.com/pborman/uuid
 - go get golang.org/x/crypto/bcrypt

before_script:
 - psql -c "CREATE ROLE test WITH LOGIN PASSWORD 'test';" -U postgres
 - psql -c "CREATE DATABASE gin_auth OWNER test;" -U postgres
 - goose -path conf up

script:
 - fgt golint -min_confidence 0.9 ./...
 - go test -v -covermode=count -coverprofile=profile-data.cov.part ./data
 - go test -v -covermode=count -coverprofile=profile-util.cov.part ./util

after_success:
 # collect all coverage profiles
 - "echo \"mode: count\" > profile.cov"
 - "grep -h -v \"mode: count\" *.cov.part >> profile.cov"
 # upload coverage profile
 - goveralls -coverprofile=profile.cov -service=travis-ci